application: aits-test
version: 1-3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*)
  script: bs2grproxy.aitsapp

libraries:
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: 2.6
